### ISSUE TITLE
General question about cross-compilation

### ISSUE THREAD

**Issue by danpetry** [conda-forge/cuda-cudart-feedstock#19]
### Comment:

There are a couple of patterns used here which look like they're there to support cross-compilation: embedding `{{ target_platform }}` in the package name and making them noarch: generic; including `$targetsDir` in the paths where headers and libraries are installed. Is this the purpose for this just to check my understanding?

**Comment by jakirkham** [comment]
Yep that's right

Packages that have names with `{{ target_platform }}` in them can be installed on `{{ build_platform }}`s (where `build_platform != target_platform`). Of course they can also be installed in cases where the two are the same

https://github.com/conda-forge/cuda-cudart-feedstock/blob/a317588c669cde9dee58ccc8bb0cd22c69d4a4a6/recipe/meta.yaml#L31-L36

The `$targetsDir` structure is something NVCC is familiar with and is used to enable cross-compilation. A little bit of remapping from Conda-Build's `{{ target_platform }}` is needed to construct `$targetsDir` as expected

https://github.com/conda-forge/cuda-cudart-feedstock/blob/a317588c669cde9dee58ccc8bb0cd22c69d4a4a6/recipe/build.sh#L9-L11

All of the CUDA packages use the `$targetsDir` structure

Only some of them include `{{ target_platform }}` in their names. This is done for packages that are to be installed in the `build` environment (usually needed as part of a working NVCC install)

Key use cases where cross-compilation comes up in conda-forge involve building on `linux_64` and targeting some other `linux_*` (like `linux_aarch64`). This comes up as it is currently easier to find build resources on `x86_64` than it is other architectures. Though this may change over time

There is more background on this in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/1963 )

**Comment by danpetry** [comment]
Thanks for the detailed information. Also interesting to understand more about c-f's cross-compilation use cases in general.

**Comment by jakirkham** [comment]
It is kind of the same idea in the general case. Trying to leverage resources we have to support a wider range of targets

Though that is probably best discussed in a new issue
